FROM node:22-alpine

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos de dependências
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante dos arquivos do projeto
COPY . .

# Expõe a porta usada pela aplicação
EXPOSE 3001

# Comando para iniciar a aplicação
CMD ["node", "index.js"]